#!/usr/bin/env bash
#
# render-report.sh <findings.tsv> <n_repos> <n_skipped> <dev_root>
#
# Turns the TSV that dev-audit.sh produced into a dated markdown report on
# stdout. Kept separate from the checks so a report can be re-rendered from an
# old TSV without re-running the sweep.
#
# The report inherits the same rule as the checks: it names files and rules,
# never matched values.

set -u
TSV="${1:?findings tsv}"
N_REPOS="${2:-0}"
N_SKIP="${3:-0}"
DEV_ROOT="${4:-$HOME/dev}"

count() { LC_ALL=C grep -c "^$1	" "$TSV" 2>/dev/null || echo 0; }

cat <<HDR
# Workspace audit — $(date +%Y-%m-%d)

Generated by \`dotfiles/scripts/dev-audit.sh\`. Read-only: nothing in
\`$DEV_ROOT\` was created, modified or deleted to produce this.

**Do not commit this file.** It names private paths and any secret-shaped
findings by location. See \`dotfiles/docs/dev-audit.md\`.

Scope: $N_REPOS repos, $N_SKIP skipped.
Findings: **$(count FAIL) FAIL**, $(count WARN) WARN, $(count INFO) INFO.

HDR

section() {
  local cat="$1" title="$2" body
  body="$(LC_ALL=C awk -F'\t' -v c="$cat" '$2==c' "$TSV" 2>/dev/null)"
  [ -n "$body" ] || return 0
  printf '## %s\n\n' "$title"
  printf '| Severity | Repo | Check | Detail |\n|---|---|---|---|\n'
  # Sort FAIL first, then WARN, then INFO; alphabetical within each.
  printf '%s\n' "$body" | LC_ALL=C awk -F'\t' '
    { rank = ($1=="FAIL") ? 0 : ($1=="WARN") ? 1 : 2
      printf "%d\t%s\t%s\t%s\t%s\n", rank, $1, $3, $4, $5 }' \
    | LC_ALL=C sort -t'	' -k1,1n -k3,3 \
    | LC_ALL=C awk -F'\t' '{ printf "| %s | `%s` | %s | %s |\n", $2, $3, $4, $5 }'
  printf '\n'
}

section git     "Git hygiene"
section policy  "Policy compliance (CLAUDE.md)"
section privacy "Privacy and secrets"
section disk    "Disk and backup exposure"

cat <<'FTR'
## How to read this

- **FAIL** — work or data at risk, or a stated rule broken. Act on these.
- **WARN** — drift worth fixing, no immediate risk.
- **INFO** — inventory, not a problem. Dirty working trees live here on
  purpose: a dirty tree is normal mid-task, it only matters in aggregate.

Nothing here is fixed automatically. `dev-audit.sh` has no `--fix` mode by
design — 89 repos is too many to let a script loose in.
FTR
