tap "hashicorp/tap"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
tap "plasma-umass/scalene"
tap "redis-stack/redis-stack"
tap "romkatv/powerlevel10k"
tap "supabase/tap"
tap "xcodesorg/made"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Official Amazon AWS command-line interface
brew "awscli"
# Python code formatter
brew "black"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Command-line interface for Cabal and Hackage
brew "cabal-install"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Lightweight unit testing framework for C
brew "cunit"
# Command-line tool to interact with exercism.io
brew "exercism"
# XML 1.0 parser
brew "expat"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Play, record, convert, and stream audio and video
brew "ffmpeg@6"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Open-source distributed event streaming platform
brew "kafka"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# Java-based project management
brew "maven"
# NCurses Disk Usage
brew "ncdu"
# Small build system for use with gyp or CMake
brew "ninja"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Open source computer vision library
brew "opencv"
# Outputs current CPU temperature for OSX
brew "osx-cpu-temp"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# General-purpose scripting language
brew "php"
# Object-relational database system
brew "postgresql@17"
# Theme for zsh
brew "powerlevel10k"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Messaging and streaming broker
brew "rabbitmq"
# Rsync for cloud storage
brew "rclone"
# Persistent key-value database, with built-in net interface
brew "redis"
# Tool for downloading RTMP streaming media
brew "rtmpdump"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Unsupervised text tokenizer and detokenizer
brew "sentencepiece"
# Contract-oriented programming language
brew "solidity"
# Tool to create intelligent and beautiful documentation
brew "sphinx-doc"
# Command-line tool to customize Spotify client
brew "spicetify-cli"
# Header-only C++ library for printing colored messages
brew "termcolor"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# Modular BSD reimplementation of NASM
brew "yasm"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Centralized server for distributed coordination of services
brew "zookeeper"
# UNIX shell (command interpreter)
brew "zsh"
# Install and switch between multiple versions of Xcode
brew "xcodesorg/made/xcodes", trusted: true
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Installs a Redis server with additional database capabilities
cask "redis-stack/redis-stack/redis-stack-server"
# Rust-based terminal
cask "warp"
vscode "afractal.node-essentials"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "astro-build.astro-vscode"
vscode "augment.vscode-augment"
vscode "be5invis.vscode-icontheme-nomo-dark"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.path-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "firsttris.vscode-jest-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "htmlhint.vscode-htmlhint"
vscode "ibm.output-colorizer"
vscode "jasonnutter.search-node-modules"
vscode "juanblanco.solidity"
vscode "kamikillerto.vscode-colorize"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vsliveshare.vsliveshare"
vscode "orta.vscode-jest"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "rvest.vs-code-prettier-eslint"
vscode "steoates.autoimport"
vscode "trishantpahwa.express-generator"
vscode "twxs.cmake"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vmware.vscode-boot-dev-pack"
vscode "vmware.vscode-spring-boot"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscjava.vscode-spring-boot-dashboard"
vscode "vscjava.vscode-spring-initializr"
vscode "vscode-icons-team.vscode-icons"
vscode "wallabyjs.quokka-vscode"
vscode "wix.vscode-import-cost"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
npm "@anthropic-ai/claude-code"
npm "vercel"
